### ISSUE TITLE
Recent "Unable to tune channel" issues

### ISSUE THREAD

**Issue by tombowditch** [tellytv/telly#108]
Please record findings here.

**Comment by tombowditch** [comment]
After a quick look...

> 
> [14:00] Tom: my thoughts so far:
> [14:00] Tom: 
> ```
> Jun 15, 2018 12:59:53.331 [0x7fcdf57ff700] VERBOSE - WebSocket: processed 1 frame(s)
> Jun 15, 2018 12:59:53.370 [0x7fcde83ff700] ERROR - [Transcoder] [hls,applehttp @ 0x26dad00] Start sequence (0) is bigger than the segment count (0).
> Jun 15, 2018 12:59:53.459 [0x7fcdf0fff700] ERROR - [Transcoder] Option scan_all_pmts not found.
> Jun 15, 2018 12:59:53.460 [0x7fcde2fff700] VERBOSE - JobManager: child process with PID 850 exited
> Jun 15, 2018 12:59:53.460 [0x7fcde2fff700] DEBUG - Jobs: '/usr/lib/plexmediaserver/Plex Transcoder' exit code for process 850 is 1 (failure)
> ```
> 
> 
> this scan_all_pmts option is causing the transcoder to exit
> if i copy the command that the transcoder runs directly and remove -scan_all_pmts it forks properly and i can see it trying to load in telly log
> [14:01] Tom: someone mentioned here it works on windows ?
> [14:01] Tom: i wonder if scanallpmts isnt on windows hence not this problem
> [14:01] Tom: https://ffmpeg.org/pipermail/ffmpeg-devel/2014-November/164943.html
> [14:01] Tom: ffmpeg version related ?

**Comment by HazCod** [comment]
So this is only related to HLS and not MPEGTS?

**Comment by tombowditch** [comment]
Me and @EnorMOZ been working through some debugging, think we've found the issue.

Updates to follow

**Comment by nroTTron** [comment]
Plex Media Server log is not logging any warnings or errors when I get the Playback error on Windows 10. Any ideas why not?

**Comment by tombowditch** [comment]
@nroTTron open your .m3u, find one of the URLs. Does it end in `.ts`?

**Comment by nroTTron** [comment]
It has .ts.  For the sake of this open ticket, I will test with non-Vaders M3u.

**Comment by nroTTron** [comment]
FYI - I was just able to get a non-Vaders m3u to work on Win 10 ONLY if I select a built-in Plex EPG. I used a random service provider with US zipcode. No Playback Error. 

When I try to load the provider XML, Plex fails to complete the guide setup process. It just keeps spinning the continue button on an endless loop. So I will add this in the other mapping thread as well.

**Comment by tombowditch** [comment]
Okay, tl;dr I think either Plex is no longer supporting .m3u8 streams or there's a bug in the recent version.

I recommend switching to using MPEG-TS (.ts) streams - most if not all providers support this by adding `&output=ts` to where you grab your .m3u

Keeping this open to track progress. If Plex don't fix this then I'll work on a transcoder .m3u8 -> .ts

**Comment by tombowditch** [comment]
Copy and pastable sed:

```
sed -i 's/.m3u8/.ts/g' your.m3u
```

**Comment by hthighway** [comment]
Using vaders with the`&format=ts` option I can get telly 0.6.2 to start without the m3u8 warings.  Plex sees it as a tuner and Plex scans the channels fine, and then it will load my epg file.   

But when all that is done I still get a `playback error`   

I've tried this one two separate boxes, both running Ubuntu 16.04 and PMS 1.13.2.5154.
Once box uses docker and the other is just running on linux

**Comment by nroTTron** [comment]
I am getting Playback error when I use my external XML now.

**Comment by SdlasHeras** [comment]
Hi @tombowditch 
Video working on Windows 10 Pro, telly v0.6 and Plex 1.13.2.5154

**Comment by Man-in-Black** [comment]
How did you get this to work?
My m3u-File does not end in `.ts`

**Comment by Joost1991** [comment]
Using .ts m3u file and I also got a Playback error.

Using Plex 1.13.2.5154 on Ubuntu 16.04 and telly 0.6.2.

**Comment by mediaman88** [comment]
Everything was working great for the last two days, now all of a sudden I can't play anything.  Both PMS and Telly running on Windows 10.  I am using the .ts version of Vaders m3u.

All channels work fine using the plug-in method through plex, but nothing will play from the DVR Guide.

**Comment by soosthui** [comment]
Running Telly on Windows 10 NUC pc, Running Plex Server on QNAP servers. 

I get playback errors when using Telly 6.2 or 6.0 but if I use version 5.0 or 4.5 all my channels play perfectly fine in Plex.

What is different from Telly 5.0 to 6.2?

**Comment by willbeeching** [comment]
I'm also getting 'Unable to tune channel' using the latest Telly version and latest PMS. All the streams contained within my m3u file are .ts, when I click on the channel and see Telly redirecting to the stream in terminal I can copy and paste that into VLC and it starts fine, so the right stream is definitely getting parsed. 

Has anyone found a solution to this?

**Comment by Man-in-Black** [comment]
Same issue here.
If I copy the redirected URL directly into VLC it works like a charm.
With PMS I cannot stream anything. This issue occurs with telly 5.0 and 6.2.

**Comment by porkie02** [comment]
There is a few things you need you need to checklist.

- Do the stream links end in .ts? Here is a example of my links that are working http://live.eternaltv.net:25461/live/xxxxx/xxxxxx/22419.ts

-  Have you set the base url command? Do not use localhost or 0.0.0.0, -base=192.168.x.x:6077

- Have tried the listen command? Again do not use localhost or 0.0.0.0, -listen=192.168.x.x:6077

For me using the docker container -base was enough for me for it to work, also whenever you change any setting make sure just in case to restart pms. I hope this helps some people.

**Comment by BDS369** [comment]
can you please explain how? FYI, I am using xtreme-editor to edit the playlist. 
So it might have to be done on there- but I can't figure out how

**Comment by porkie02** [comment]
just change the output of the link from Vader, Vader are very good at you being able to use different links but that can cause a lot of confusion also. I use XE to and I just use the api link they provide through minihosts which is http://api.vaders.tv/vget?username=xxxx&password=xxxxx&format=ts

**Comment by BDS369** [comment]
thank you very much! working now

**Comment by MichealX64** [comment]
I was also receiving this error message and setting the -base= parameter fixed it for me!

> Have you set the base url command? Do not use localhost or 0.0.0.0, -base=192.168.x.x:6077

Thank you @porkie02

**Comment by ArtursGailis1995** [comment]
My IPTV is only available in M3U or M3U8 format which then contains chunks of TS files.

This is the format I receive it:
> playlist.m3u8?authtoken=blahblah > chunklist_channelname_id.m3u8?authtoken=blahblah > media_channelname_id_id.ts?authtoken=blahblah.

Any chance it will be fixed soon? Just moved from Emby to Plex.

**Comment by live4ever** [comment]
I got around this by adding the base var to the docker container as well (m3u file with .ts):

![base](https://user-images.githubusercontent.com/619870/42706490-fa5c1722-86a4-11e8-95bd-0a04359b32ce.PNG)

**Comment by b101marc** [comment]
Having an issue with crashing. I'm using PlayersKlub using the .ts output with no success. Any other suggestions? Relative newcomer.

**Comment by causefx** [comment]
Heads up, if guide xml has a space in the channel ID, you will get the tune error.

**Comment by 91ajames** [comment]
where do you put this "sed -i 's/.m3u8/.ts/g' your.m3u"
does it work or is there no solutions to this yet?

**Comment by robbiet480** [comment]
I [found a script on StackOverflow](https://stackoverflow.com/a/48807847/486182) which filters out arguments passed into a script. I moved `/usr/lib/plexmediaserver/Plex Transcode` to `/usr/lib/plexmediaserver/old-PT` and then put the script at `/usr/lib/plexmediaserver/Plex Transcode` (taking care to match permissions. Now i've got a working telly 😎!

Here's my slightly modified version of the linked script to remove the debug `echo`'s and specifically strip out `scan_all_pmts`.

```bash
#!/bin/bash

function arg_remove ()
{
    local array=("${@:3}")

    for ((i=0; i<"${#array[@]}"; ++i)); do
        case ${array[i]} in
            "$2") unset array[i]; unset array[i+1]; break ;;
        esac
    done

    # clean up unset array indexes
    for i in "${!array[@]}"; do
        new_array+=( "${array[i]}" )
    done
    array=("${new_array[@]}")
    unset new_array

    # assign array outside function scope
    local -g "$1=(  )"
    eval ${1}='("${array[@]}")'
}

arg_remove ARG_PASS '-scan_all_pmts' "$@"
/usr/lib/plexmediaserver/Plex Transcoder/old-PT "${ARG_PASS[@]}"
```

**Comment by simonk83** [comment]
Just chiming in here that I'm trying to work through this as well.  I'm using the following link for Australian Freeview channels, which unfortunately are all m3u8 (I haven't found any other working options as yet) - https://raw.githubusercontent.com/matthuisman/iptv/a3dd5861a72dafc46545bead266e37f777212eaf/au/Melbourne/raw-tv.m3u8

Getting the tune error, which is to be expected I suppose :)    Other than that, everything is showing up in Plex perfectly, well done Tom.  Looking forward to being able to get this fully working,

**Comment by robbiet480** [comment]
Should be fixed by https://github.com/tellytv/telly/commit/2130ad62bf17f6279a2201a7badaeecd60070fe9, using ffmpeg to transcode streams to a Plex acceptable format
