### ISSUE TITLE
Allow custom channel mapping

### ISSUE THREAD

**Issue by tombowditch** [tellytv/telly#109]
Should stop people having to spend hours fiddling with Plex UI. Would be a "channels.json" file or something similar with the format something like... 

```
"channels": [
    {
        "channelNumber": "101",
        "channelName": "BBC One HD",
    },
    {
        "channelNumber": "102",
        "channelName": "BBC Two HD",
    },
    ... you get the point
]

```

etc.

Will be coming shortly.

**Comment by HazCod** [comment]
The channel name should be a regular expression or wildcard match too, as IPTV providers often append extra information before/after the channel name.

**Comment by tombowditch** [comment]
Agreed, we cannot match one channel number to multiple channels though, as Plex will tell us "no"

**Comment by chazlarson** [comment]
PlexIPTV has a pretty nice implementation of this.
https://github.com/xiaodoudou/PlexIPTV

**Comment by nroTTron** [comment]
FYI - I was just able to get a non-Vaders m3u to work on Win 10 ONLY if I select a built-in Plex EPG. I used a random service provider with US zipcode. No Playback Error. 

When I try to load the provider XML, Plex fails to complete the guide setup process. It just keeps spinning the continue button on an endless loop. So I will add this in the other mapping thread as well.

**Comment by nroTTron** [comment]
FYI - I am able to get past the channel loading with IPTV XML by deleting DVR and restarting PMS a few times. Waiting for guide to load.  

**#EXTINF:-1 tvg-id="US: A&E" tvg-name="US: A&E" tvg-logo="http://IPTVDOMAIN/guide/logos/AE.png" group-title="USA",US: A&E http://IPTVDOMAIN:PORT/live/xxxx/xxxxx/30.ts**

**Comment by guyspr** [comment]
@nroTTron this issue seems to be resolved. If not, please re-open if any other issues.
