### ISSUE TITLE
Fallback when tvg-name is blank

### ISSUE THREAD

**Issue by tombowditch** [tellytv/telly#110]
e.g.:

```
#EXTINF:-1 tvg-id="" tvg-name="" tvg-logo="" tvg-chno="8" group-title="Latino",some-otherchannel-name-here
```

Should fallback to use `some-otherchannel-name-here`

would be a job for https://github.com/tombowditch/telly-m3u-parser

**Comment by robbiet480** [comment]
Taken care of on dev branch!
