### ISSUE TITLE
telly transcoder

### ISSUE THREAD

**Issue by tombowditch** [tellytv/telly#115]
With the recent issues it's obvious telly is going to need some sort of transcoding solution in the future.

I am thinking something to do with ffmpeg? Plex seems to like `.ts. / MPEG-TS.

**Comment by HazCod** [comment]
There are go bindings available for ffmpeg: https://github.com/giorgisio/goav
Funny enough, while Plex likes MPEG-TS, they use HLS to stream from the server to the client.

**Comment by frznman** [comment]
Is converting really necessary? My m3u8s have .ts in them. Wouldn't Plex be able to read those?

**Comment by gitAuss1e** [comment]
Any update on this? Thanks!

**Comment by lobosrul** [comment]
On a related note , I'm using ffmpeg to record iptv with "-stimeout 10000000" set. Seems a much more reliable way to record, with Plex about a quarter of everything I record has an error. Would be worth piping the output of ffmpeg into Plex?

**Comment by robbiet480** [comment]
Fixed via https://github.com/tellytv/telly/commit/2130ad62bf17f6279a2201a7badaeecd60070fe9
