### ISSUE TITLE
Transcoder failure after 10-20 sec

### ISSUE THREAD

**Issue by bhaap** [tellytv/telly#118]
After 10-20sec in a live-tv stream the stream always closes and throws an error.
I've been looking at the plex media server log and the only thing that stands out is this:

```
un 19, 2018 22:58:59.718 [9872] DEBUG - Completed: [127.0.0.1:61899] 200 GET /livetv/sessions/c8fc4d80-d237-4063-b553-82a387de6403/5wj6nxxa128f5ohcn5mdamif/00017.ts (20 live) 4ms 109792 bytes (pipelined: 1)
Jun 19, 2018 22:58:59.787 [8316] DEBUG - Transcoder segment range: 0 - 35
Jun 19, 2018 22:58:59.799 [2612] ERROR - Caught exception trying to stream file: C:\Users\MJP\AppData\Local\Plex Media Server\Cache\Transcode\Sessions\plex-transcode-c8fc4d80-d237-4063-b553-82a387de6403\media-00017.ts: write: En begäran att skicka eller ta emot data tilläts inte eftersom socketen redan avslutats i den riktningen vid ett tidigare anrop
Jun 19, 2018 22:58:59.801 [10540] DEBUG - Completed after connection close: [127.0.0.1:61752] 500 GET /livetv/sessions/c8fc4d80-d237-4063-b553-82a387de6403/5wj6nxxa128f5ohcn5mdamif/00017.ts (22 live) 88ms 0 bytes (pipelined: 3)
Jun 19, 2018 22:58:59.915 [8796] DEBUG - Transcoder segment range: 0 - 36
```
basiclly that swedish text says:
A request to send or receive data was disallowed because the socket had already been shut down in that direction with a previous shutdown call.

And that is a Windows Sockets error:
WSAESHUTDOWN 10058

**Comment by redxon** [comment]
Same problem here, using Unraid as a server and with all the clients it does that. Strange behaviour.

**Comment by mikerohan** [comment]
Same problem... I was not even trasncoding...
I was recording a .ts stream that otherwise works ok when opened with VLC...

**Comment by guyspr** [comment]
@bhaap does this issue still persist on newer versions of Telly?

**Comment by tombowditch** [comment]
Hi folks,

As @guyspr suggested, please try the dev branch (especially the ffmpeg one)

Let us know if you're still having issues.
