### ISSUE TITLE
Changing deviceid on Windows

### ISSUE THREAD

**Issue by mediaman88** [tellytv/telly#121]
I am attempting to change the deviceid on Windows telly without luck.  I've tried every iteration of -deviceid 87654321, -deviceid "87654321", -deviceid=87654321.  

I need this for Plex to recognize a second instance of Telly to use a separate tuner.  Changing only the friendlyname did not work, still shows as a single tuner to Plex.

**Comment by robbiet480** [comment]
Should be fixed via the config file
