### ISSUE TITLE
Which version will work on WD PR4100

### ISSUE THREAD

**Issue by sneakypete73** [tellytv/telly#126]
Can you please tell me which version of telly will work on my WD PR4100, and can you please give me some simple instructions? Thanks

**Comment by Codehhh** [comment]
Looks like you're able to use Docker on that NAS. 
https://hub.docker.com/r/tombowditch/telly/

**Comment by tombowditch** [comment]
@sneakypete73 -

You need to find a way to daemonize `telly` on that NAS.

As @Codehhh said - Docker may work on the NAS. We build telly so you can pull it easily on Dockerhub @ `tombowditch/telly`, you should just be able to pull that.

T

**Comment by sneakypete73** [comment]
Following those instructions.

 

I entered:

./telly –playlist=/http://tv.hdtv4u.cc:2052/get.php?username=gordon73@gmail.com\&password=gaPQJpcKqq\&type=m3u_plus\&output=ts -uktv

 

And got: 

Unable to read m3u file

Unable to open playlist file

**Comment by tombowditch** [comment]
@sneakypete73 

Firstly, **PLEASE CHANGE YOUR PASSWORD TO YOUR IPTV ACCOUNT** - you've just gave a few hundred people your username and password.

Secondly, that command is failing because you have a / just before `http`

Change ` –playlist=/http://` to ` –playlist=http://`

T

**Comment by sneakypete73** [comment]
Ooops.

 

Now. I do indeed have docker – although I have never used it.

 

What is the first step?

 

Is it docker run, docker compose, or setup as the first step – and are all commands entered in Putty?

 

Thanks Tom

**Comment by tombowditch** [comment]
Take a look at the readme. Run something like - 

```
docker run -d \
  --name='telly' \
  --net='bridge' \
  -e TZ="Europe/Amsterdam" \
  -e 'PLAYLIST'='/home/github/myiptv.m3u' \
  -e STREAMS=1 \
  -e USEREGEX='.*UK.*' \
  -p '6077:6077/tcp' \
  -v '/tmp/telly':'/tmp':'rw' \
  tombowditch/telly -base=localhost:6077
```

**Comment by sneakypete73** [comment]
I am referring to https://hub.docker.com/r/tombowditch/telly/

Don’t see a Readme.

 

Do I have to enter both the docker run and docker compose text? And in what order? Any is this entered through Putty?

**Comment by Codehhh** [comment]
@sneakypete73 To use docker on your NAS: https://community.wd.com/t/docker-and-apps/170177/2
You should only run the `docker run` command.

**Comment by sneakypete73** [comment]
Tom I keep getting this error - can you please offer any assistance:

Unable to find image 'tombowditch/telly:latest' locally
latest: Pulling from tombowditch/telly
6763caf1f9ee: Pull complete
4417fed44ce9: Pull complete
Digest: sha256:dc661e56656217642db91f0a4c6ad53e048b41a4173057d7b20bef0bbe8fe570
Status: Downloaded newer image for tombowditch/telly:latest
docker: Error response from daemon: Conflict. The container name "/telly" is already in use by container "3974e747a3f69749f9cd847baa3ebf0a775ec6278ec2e8b166256b562e1faa49". You have to remove (or rename) that container to be able to reuse that name.

**Comment by Codehhh** [comment]
@sneakypete73 You already have a docker named `telly`. You have to either remove (or rename) the container.
`docker stop telly && docker rm telly` will stop the current `telly` instance and remove it. Then you can proceed with pulling the new container.

**Comment by sneakypete73** [comment]
Thanks. I since stopped telly and purged all containers.

 

I enter:

 

docker run -d \

  --name='telly' \

  --net='bridge' \

  -e TZ="Europe/Amsterdam" \

  -e 'TELLY_IPTV_PLAYLIST'='/home/github/myiptv.m3u' \

  -e TELLY_IPTV_STREAMS=1 \

  -e TELLY_FILTER_REGEX='.*UK.*' \

  -p '6077:6077/tcp' \

  -v '/tmp/telly':'/tmp':'rw' \

  tombowditch/telly --listen.base-address=localhost:6077

 

where /home/github/myiptv.m3u is a http address

 

I receive: 

 

Unable to find image 'tombowditch/telly:latest' locally

latest: Pulling from tombowditch/telly

6763caf1f9ee: Pull complete

4417fed44ce9: Pull complete

Digest: sha256:dc661e56656217642db91f0a4c6ad53e048b41a4173057d7b20bef0bbe8fe570

Status: Downloaded newer image for tombowditch/telly:latest

699951f6e36635235a586179fe4167b43c43d181bf0d1da84d278fb1bde2c057

 

I get no error and it then it returns to command line. But Plex doesn’t find anything.

 

Am I missing something?

**Comment by slawekm** [comment]
@sneakypete73 Try this:
``
docker run --rm --detach \
--name=telly \
--net=host \
-e TZ="Europe/Amsterdam" \
-e 'TELLY_IPTV_PLAYLIST'='/home/github/myiptv.m3u' \ 
-e TELLY_IPTV_STREAMS=1 \
-e TELLY_FILTER_REGEX='.*UK.*' \
tombowditch/telly --listen.base-address=0.0.0.0:6077
``

**Comment by sneakypete73** [comment]
Thanks but no good:

 

docker: invalid reference format.

 

If anyone can offer a simply step-by-step guide for Putty I’d be eternally grateful. I’m using a http address for the m3u

 

Assume I know nothing…. sorry

**Comment by slawekm** [comment]
@sneakypete73 my bad, didn't test it locally..

 How about this one? 

```
docker run --detach --rm --name telly --net=host\
 -e 'TZ=Europe/Amsterdam'\
 -e 'TELLY_IPTV_PLAYLIST=/home/github/myiptv.m3u'\
 -e 'TELLY_FILTER_REGEX=.*UK.*'\
 tombowditch/telly --web.base-address=127.0.0.1:6077
```
(I've dropped `TELLY_IPTV_STREAMS` which seems to be redundant as it's set to default value). 

You need to provide real playlist file in that location too (or mount via `-v` switch from host).

I've also noticed that you can't specify `0.0.0.0:6077` address - which should be desirable when you want to expose service outside the local machine. I'm getting this error instead:

```
time="2018-08-14T14:54:50Z" level=panic msg="base URL is set to 0.0.0.0, this will not work. please use the --web.base-address option and set it to the (local) ip address telly is running on."
panic: (*logrus.Entry) (0xaf0d60,0xc42007c870)
```

**Comment by Codehhh** [comment]
@sneakypete73 To see the docker logs after starting the container, run `docker logs telly`

**Comment by sneakypete73** [comment]
Thanks

 

How do I remove filtering?

**Comment by chazlarson** [comment]
@sneakypete73 If you remove `TELLY_FILTER_REGEX` you'll want to add `TELLY_REGEX_INCLUSIVE`.  The default regex behavior is now "blacklist" so running with no regex means "exclude everything".  Adding the inclusive flag flips that to "include everything".

**Comment by sneakypete73** [comment]
My problem seems to be the categories. If I filer with *UK.* or *UK* I don’t get UK channel – everything but UK. If I filter with *UK Entertainment.* I get UK channels but I 4880 channels. I can’t seem to narrow it down to just the 100 or so UK channels I want.

**Comment by chazlarson** [comment]
The regex behavior defaults to working as a blacklist.

This:
```
docker run --detach --rm --name telly --net=host \
-e 'TZ=Europe/Amsterdam' \
-e 'TELLY_IPTV_PLAYLIST=http://tv.hdtv4u.cc:2052/get.php?username=********&password=********&type=m3u_plus&output=ts'\
-e 'TELLY_FILTER_REGEX=.*UK.*' \
tombowditch/telly --web.base-address=127.0.0.1:6077
```
Is stripping channels that match the regex.

This:
```
docker run --detach --rm --name telly --net=host \
-e 'TZ=Europe/Amsterdam' \
-e 'TELLY_IPTV_PLAYLIST=http://tv.hdtv4u.cc:2052/get.php?username=********&password=********&type=m3u_plus&output=ts'\
-e 'TELLY_FILTER_REGEX=.*UK.*' \
-e 'TELLY_FILTER_REGEX_MODE=TRUE' \
tombowditch/telly --web.base-address=127.0.0.1:6077
```
will flip that and strip everything EXCEPT those that match the regex.

**Comment by sneakypete73** [comment]
It works at last – thanks all for your help
