### ISSUE TITLE
Installed Telly via QNAPclubstore .qpgk but wont run

### ISSUE THREAD

**Issue by jurgy15** [tellytv/telly#133]
Pretty new at this IPTV and QNAP CLI stuff but heres what i did and or dorked up.  I downloaded and installed telly from the qnap clubstore.  The NAS says that Telly has been installed and is up and running.  I try to add the m3u and all it ever says is done.  When i go to plex to see if is show up there is no tuner.  I have unistalled/reinstalled multiple times.  just trying to start telly with telly.sh start i get a return of no such file or directory but I can see the directory in winSCP.  Any help is appriciated.

This morning I was finally able to manually input the ip:port for telly and it showed up.  Had too many channels.  After weening down the m3u, telly will not show in plex again.

**Comment by guyspr** [comment]
Sorry but we do not maintain this QNAP package, please contact the package maintainer.
