### ISSUE TITLE
EPG matching??

### ISSUE THREAD

**Issue by bodgeuppm** [tellytv/telly#134]
Does Telly provide plex with EPG channel IDs? Ive got my xml file in telly 620 channels, but most map in the EPG wrong so its a nightmare to match them.  My IPTV provider has lots of duplicate channels which allow us to find working channels if there is a problem.  But i managed to got 21000 down to 620 for UK channels but still 620 to manually ID for the EPG is just not ideal.  Is there anyway to help me match the channels?

**Comment by bodgeuppm** [comment]
many thanks ill try that site for the epg see if it will help,
Great program though you answered my wish when you developed it.
look forward to more features.
I would like to see proxying of the iptv so that the provider doesn't know multiple connections from different ips are used, PlexIPTV has this but its not compiled so ive not been able to get it working on linux but if that could be integrated into telly somehow it would be amazing.

Bodgeup

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by 12nick12** [comment]
I can't wait till this is implemented that way I quit using PlexIPTV.

**Comment by niXta1** [comment]
Isn't the stream going through telly and therefore the provider only sees that IP no matter of the client?

**Comment by 12nick12** [comment]
Correct.

**Comment by fabakhti** [comment]
@chazlarson iptv-epg.com is a good service but how would I use the EPG with telly and Plex? I can only pass telly the m3u and can't see where the EPG from that service can get used. 

> One way to do what you want would be to run your M3U through iptv-epg.com and use their EPG. If you use both M3u and EPG that iptv-epg provide, all the channels will match automagically.

**Comment by chazlarson** [comment]
When you configure the DVR in Plex, there's a screen that asks for a post code.  At the top of that dialog is an orange link.  Click it and you can paste in the EPG URL from iptv-epg.com.

**Comment by guyspr** [comment]
No response for over a week, looking at the conversation I think this has been resolved.
