### ISSUE TITLE
unknown short flag '-b'

### ISSUE THREAD

**Issue by D34DC3N73R** [tellytv/telly#141]
I see the environment variables have been updated for the telly docker-compose template. I'm now getting the following error when trying to run telly.
`app: error: unknown short flag '-b', try --help`
The command is `-base=telly:6077` but it's not picking up the rest of the string, even when using quotes. when I use -filterregex, preceding `-base` I get the error `app: error: unknown short flag '-f', try --help`.

**Comment by D34DC3N73R** [comment]
removing the command section entirely allows telly to run, but regex is not filtering.

**Comment by D34DC3N73R** [comment]
This is the regex I'm trying to use `TELLY_FILTER_REGEX=.*US:.*\n.*|.*CA:.*\n.*`

Here is part of the m3u8 contents:
` #EXTINF:-1 tvg-id="" tvg-name="EFL: Swansea City v Preston North End 3pm (Live During Events Only)" tvg-logo="http://necro.to/images/channels/Efl.png" group-title="EPL | EFL",EFL: Swansea City v Preston North End 3pm (Live During Events Only)
http://necro.to:80/live/XXXXXXXXXXXXXXXXX/36jD80nshJ/7467.ts
#EXTINF:-1 tvg-id="aande.us" tvg-name="US: A&E HD" tvg-logo="http://necro.to/images/channels/A&Ehd.png" group-title="US: | United States",US: A&E HD
http://necro.to:80/live/XXXXXXXXXXXXXXXXX/36jD80nshJ/3876.ts
#EXTINF:-1 tvg-id="aande.ca" tvg-name="CA: A&E HD" tvg-logo="http://necro.to/images/channels/A&Ehd.png" group-title="CA: | Canada",CA: A&E HD
http://necro.to:80/live/XXXXXXXXXXXXXXXXX/36jD80nshJ/7406.ts`

I'm expecting 293 matches (that's what I get when parsing the whole file at regex101), but telly returns all 1423 entries.

**Comment by RhvsW** [comment]
Make sure you're testing with the golang flavor.

**Comment by D34DC3N73R** [comment]
Yes I am testing with the golang flavor. I get the same result when removing the new line option as well. `TELLY_FILTER_REGEX=.*US:.*|.*CA:.*`

**Comment by HazCod** [comment]
and `TELLY_FILTER_REGEX='(US|CA)'`

**Comment by D34DC3N73R** [comment]
`TELLY_FILTER_REGEX='(US|CA)'` also returns all 1423 entries.

**Comment by D34DC3N73R** [comment]
I would expect the default value of `TELLY_FILTER_REGEX_MODE` to be true, but it appears to be false.

> kingpin.Flag("filter.regex-inclusive", "Whether the provided regex is inclusive (whitelisting) or exclusive (blacklisting). If true (--filter.regex-inclusive), only channels matching the provided regex pattern will be exposed. If false (--no-filter.regex-inclusive), only channels NOT matching the provided pattern will be exposed. $(TELLY_FILTER_REGEX_MODE)").Envar("TELLY_FILTER_REGEX_MODE").Default("false").BoolVar(&opts.RegexInclusive)


After setting `TELLY_FILTER_REGEX_MODE=true` regex filters as expected. `TELLY_FILTER_REGEX='(US|CA)'`
