### ISSUE TITLE
Telly Sometimes Creating URLs that produce 404 error.

### ISSUE THREAD

**Issue by HurricaneChris** [tellytv/telly#144]
I noticed that some channels in Plex where giving me a "Playback Error: Unable to tune channel " error.  I found that when I go to http://IP_ADDRESS:PORT/lineup.json and picked the URL for the channel (http://IP_ADDRESS:PORT/stream/RANDON_TEXT) and tried to play this in VLC or enter it into a browser I got a 404 page not found error. Also with Debugging on, there was no "Parsing URI" event in the cmd. If I get the ts URL from the m3u file and attempt to play that in VLC the channel plays fine. 

This only happens on some URLs, others in the lineup.json play fine.

**Comment by robbiet480** [comment]
Does your `/stream` URL contain any `/` characters in it? If so, that's why. Fix coming in 1.1.0, hopefully next 48 hours.

**Comment by HurricaneChris** [comment]
Yup, that's exactly it. Thanks for the quick response.

**Comment by danielcbaldwin** [comment]
I am experiencing this as well but it seems to be every time not only some of the time for me.

**Comment by tombowditch** [comment]
Hi folks! We're aware - working on it!

**Comment by robbiet480** [comment]
Fixed in beta, closing!
