### ISSUE TITLE
Set a WebProxy

### ISSUE THREAD

**Issue by AndreAga** [tellytv/telly#145]
Hi guys,
I didn't read any info about the chance to add a web proxy as a configuration in order to let Telly to connect to remote channels through it.

Any idea if is it possible? It would be perfect.

Thanks.

**Comment by guyspr** [comment]
Do you mean that the buffering will go through Telly, instead of Telly just redirecting Plex to the stream?

**Comment by robbiet480** [comment]
Proxy support is in the next version of telly!

**Comment by robbiet480** [comment]
@AndreAga In the ALPHA 1.5.0 you can now set the URL of a proxy to use for a given request, as indicated by the environment variables `HTTP_PROXY`, `HTTPS_PROXY` and `NO_PROXY` (or the lowercase versions thereof). `HTTPS_PROXY` takes precedence over `HTTP_PROXY` for https requests.

The environment values may be either a complete URL or a "host[:port]", in which case the "http" scheme is assumed. An error is returned if the value is a different form.

More info [here](https://golang.org/pkg/net/http/#ProxyFromEnvironment).
