### ISSUE TITLE
When streaming one channel to plex and changing channel plex just returns to program info screen

### ISSUE THREAD

**Issue by jondmac** [tellytv/telly#148]
When streaming one channel to plex and changing channel plex just returns to program info screen instead of playing the new stream.

**Comment by HazCod** [comment]
Can you please provide us with the telly logs?

**Comment by guyspr** [comment]
@jondmac could you provide telly logs? Without any more information we cannot resolve this and will close this issue.

**Comment by tombowditch** [comment]
This sounds like a Plex bug.

Reopen if you can provide more details.
