### ISSUE TITLE
Unable to start -  error setting up schedules direct client      [31merror[0m="status code was 403, expected 2XX-3XX"

### ISSUE THREAD

**Issue by ikolsteren** [tellytv/telly#152]
Getting a 
 error setting up schedules direct client      [31merror[0m="status code was 403, expected 2XX-3XX"

running 
telly.exe --iptv.playlist=c:\telly\vget.m3u

The playlist is from vaders run by
http://vapi.vaders.tv/epg/vget?username=XXXXX&password=XXXXXX&format=ts&type=m3u_plus

Please help

**Comment by robbiet480** [comment]
Please ensure you are on the very latest beta.

**Comment by ikolsteren** [comment]
Looks like I was minutes before your latest push.  Working now.
Just setup and so far working great
