### ISSUE TITLE
EPG only Pulls from OTA

### ISSUE THREAD

**Issue by gwizdavid** [tellytv/telly#157]
I've successfully added the tuner. When adding, it finds 67 channels.  It gives me a selection of "Cable" and "United States".  I hit continue and it lists the channels under "Local Over the Air Broadcast".   If I select a channel to add and click on the drop down under "Guide Channels", it only give me a list of local OTA channels and not a complete list of cable channels.  So let's say for ESPN, I have no corresponding guide channel and so whatever I pick will list the wrong EPG data.
Is this because I have the HD Homerun device that only connects to OTA?  Of course, that device in my listing is shown as HDHomerun Extend while the telly device shows up as only HDHomerun.

**Comment by chazlarson** [comment]
Yes, Plex only allows a single EPG source across all your tuners.  The first EPG source added wins.

**Comment by gwizdavid** [comment]
Thanks!  I removed my homerun tuner and added the telly one first.  I then added my homerun back and got both pulling in the correct epg data.
Appreciate it!
