### ISSUE TITLE
Ffmpeg Beta Docker container

### ISSUE THREAD

**Issue by porkie02** [tellytv/telly#159]
The current Docker image does not install ffmpeg so container users can not use the new ffmpeg function. :)

**Comment by zenjabba** [comment]
I'm trying to build in ffmpeg, but getting the following error

`fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz`
`fetch http://dl-cdn.alpinelinux.org/alpine/v3.8/community/x86_64/APKINDEX.tar.gz`
`ERROR: http://dl-cdn.alpinelinux.org/alpine/v3.8/community: network connection aborted`

I can confirm I can manually download the files via wget outside of docker build.

**Comment by EnorMOZ** [comment]
New` dev-ffmpeg` image has been pushed.
