### ISSUE TITLE
How to install on a Synology....... or a mac?

### ISSUE THREAD

**Issue by noobey** [tellytv/telly#160]
Sorry for the inane question.
Would love to install this on my Synology DS3018xs or 916+.

If needed I have a mac laying around I could also use, but that would be a last restort.

Would still need help on the "how" though.

Appreciate any advice!

Thanks
:-)

**Comment by guyspr** [comment]
A Synology has docker (I guess), you should run it in there.

**Comment by noobey** [comment]
Happy to try it, but I have no idea which version I should be downloading as they all seem to have Intel processors?
https://www.synology.com/en-uk/knowledgebase/DSM/tutorial/General/What_kind_of_CPU_does_my_NAS_have

**Comment by guyspr** [comment]
If you can, please join the discord channel. There's also a support channel: https://discord.gg/bnNC8qX
This way we can help you better, it looks like you're not completely up to speed on how this all works.

**Comment by noobey** [comment]
Roger that, thanks. Will dig in now.

**Comment by guyspr** [comment]
@noobey I think you got it running now. Closing this.
