### ISSUE TITLE
What Filters to Use?

### ISSUE THREAD

**Issue by gwizdavid** [tellytv/telly#162]
How does --filter.regex="xxxx" work?  Is it filtering the channel name from the epg listing?  I'm not sure it does because my "sports" filter pulls in channel names without the word "sports". 
My problem is filtering channels using "US" still produces too many entries for Plex.  And some filters don't add any channels.  For instance, I would like to add in some kid's channels but I'm not sure how to pull those in beside naming each individual channel.

**Comment by D34DC3N73R** [comment]
It switched to a blacklist for some reason. So it's actually excluding everything with the word "sports" and returning the rest of your results. You need to add --regex.inclusive=true if you want it to work as a whitelist.

**Comment by guyspr** [comment]
Seems to be resolved, closing this issue.
