### ISSUE TITLE
read EPG from TVHeadend guide.xml (file mode)

### ISSUE THREAD

**Issue by alturismo** [tellytv/telly#167]
as TVH doesnt export the category, episode, ... on their ip:port/xmltv it would be nice to get telly to read the guide.xml from tvh where all the infos are ... file mode ....xml

i guess its due the different **channel ids** (nr. vs names), samples

what telly **can read** (here from xmltv TVH Server)

```
<channel id="1cb992b86ce4c2771ab2791d2958d9d1">
  <display-name>VOX HD</display-name>
  <icon src="http://192.168.1.2:9981/imagecache/921%22/%3E
</channel>
```

what telly **cant read** (from the guide.xml file generated by webgrab and TVH imports)

```
<channel id="VOX HD">
    <display-name lang="de">VOX HD</display-name>
    <icon src="https://tv-manager.vodafone.de/tv-manager/backend/epg_images_channels/4228.png" />
    <url>http://www.vodafone.de/</url>
  </channel>
```
would be a nice feature.

**Comment by tombowditch** [comment]
Are you using tvheadend and telly together? In what way?

**Comment by guyspr** [comment]
No response for over two weeks. If issue still persist, please feel free to re-open with more information.
