### ISSUE TITLE
No Channels being found in M3U file

### ISSUE THREAD

**Issue by TonyTheTechie** [tellytv/telly#172]
**telly release with the issue:**

**Last working telly release (if known):**

This is the first release I have installed 

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

**Description of problem:**
telly appears to successfully run, but it is reporting 0 channels found in the m3u file.
See screen output below Command line used
On trying to setup live tv on Plex, it finds telly, but again reports 0 channels.
If I try to scan for channels I get an error - see screen dump below

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```
Where do I find the telly.config.toml file? I can't see a file named this in my jail
```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```
[root@Telly /]# telly --iptv.playlist=/var/iptvlists/uk_280818_iptvsource_com.m3u --web.listen-address=192.168.0.52:6077
INFO[0000] Starting telly (version=1.0.3, branch=master, revision=e543e7080a57eb6d7b6dd4b0ad27b789d3aa6c08) 
INFO[0000] Build context (go=go1.10.3, user=root@21d9dfe90d82, date=20180811-23:24:04) 
INFO[0000] found 0 channels                             
INFO[0000] requests_total registered.                   
INFO[0000] request_duration_seconds registered.         
INFO[0000] response_size_bytes registered.              
INFO[0000] request_size_bytes registered.               
INFO[0000] Listening and serving HTTP on 192.168.0.52:6077 

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**
<img width="704" alt="screenshot 2018-08-28 22 24 56" src="https://user-images.githubusercontent.com/21354214/44734098-54309b00-ab13-11e8-9fc3-407ee012c7b5.png">

**Comment by D34DC3N73R** [comment]
Notice the note about channel filtering in README.md

> Regex handling changed in 1.0. `filter.regex` has become blacklist which defaults to blocking everything. If you are not using a regex to filter your M3U file, you will need to add at a minimum `--regex.inclusive=true` to the command line. If you do not add this, telly will by default EXCLUDE everything in your M3U. The symptom here is typically telly seeming to start up just fine but reporting 0 channels.

**Comment by chazlarson** [comment]
This walkthrough in the wiki may help.  There's a demo of this very situation.
https://github.com/tellytv/telly/wiki/Standalone-Walkthrough%3A-Linux

**Comment by TonyTheTechie** [comment]
Thanks D34DC3N73R. That has pointed me in the right direction. Format of the option has changed in the current release (it is now —filter.regex-inclusive), so now my m3u file is showing 55 channels.

Many thanks for your help.

**Comment by chazlarson** [comment]
Thanks; I've fixed the error in the readme.
