### ISSUE TITLE
DOCKER issue

### ISSUE THREAD

**Issue by waynemillskidals** [tellytv/telly#179]
Ran using composer and stuck on 'restarting'

`sudo docker ps
CONTAINER ID        IMAGE                       COMMAND                  CREATED             STATUS                              PORTS                              NAMES
ed5d681aacf8        tellytv/telly               "./app -base=telly..."   4 minutes ago       Restarting (1) About a minute ago                                      telly_telly_1
`

when I view the logs I can see this
```

sudo docker logs ed5d681aacf8
app: error: 'telly:6077' is not a valid TCP address: lookup telly on 8.8.8.8:53: no such host, try --help
app: error: 'telly:6077' is not a valid TCP address: lookup telly on 8.8.8.8:53: no such host, try --help
app: error: 'telly:6077' is not a valid TCP address: lookup telly on 8.8.8.8:53: no such host, try --help
app: error: 'telly:6077' is not a valid TCP address: lookup telly on 8.8.8.8:53: no such host, try --help
```

**Comment by chazlarson** [comment]
What are your docker network settings?  I suspect that you want the telly docker on a particular named network.

For example, I'm using cloudbox and all my dockers are on a cloudbox network.  I can't refer to them by name outside the docker network, but inside one of the dockers the names work.

```
➜  ~ curl nzbget:6789
curl: (6) Could not resolve host: nzbget
➜  ~ docker exec -ti plex /bin/bash
root@9c0aeb27af44:/# curl nzbget:6789 | head
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
<!DOCTYPE html>
<!--
 * This file is part of nzbget. See <http://nzbget.net>.
 *
 * Copyright (C) 2012-2017 Andrey Prygunkov <hugbug@users.sourceforge.net>
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
```

**Comment by D34DC3N73R** [comment]
I ran into the same issue. Using localhost or 127.0.0.1 worked in bridge, but I ended up using host network mode and LAN IP of the host machine. (Plex also host network mode same machine.)

**Comment by guyspr** [comment]
@waynemillskidals has your issue been resolved with the above comments?

**Comment by guyspr** [comment]
No response in the past week. Closing, feel free to re-open with more information if you are still experiencing issues.
