### ISSUE TITLE
I/O Timeout when loading M3U

### ISSUE THREAD

**Issue by lellimecnar** [tellytv/telly#183]
I'm seeing the following in my Docker container (`tellytv/telly-ffmpeg`) on startup:

```
time="2018-09-01T14:44:56Z" level=info msg="telly is preparing to go live (version=, branch=, revision=)"
time="2018-09-01T14:44:58Z" level=info msg="Loading M3U from http://api.vaders.tv/vget?username=REDACTED&password=REDACTED&vod=false&format=ts" 
time="2018-09-01T14:45:28Z" level=error msg="unable to get m3u file" error="Get http://api.vaders.tv/vget?username=________&password=________&vod=false&format=ts: dial tcp 185.102.218.3:80: i/o timeout" 
time="2018-09-01T14:45:28Z" level=error msg="error when preparing provider" error="Get http://api.vaders.tv/vget?username=________&password=________&vod=false&format=ts: dial tcp 185.102.218.3:80: i/o timeout" 
time="2018-09-01T14:45:28Z" level=error msg="error when processing provider" error="Get http://api.vaders.tv/vget?username=________&password=________&vod=false&format=ts: dial tcp 185.102.218.3:80: i/o timeout" 
time="2018-09-01T14:45:28Z" level=info msg="telly is live and on the air!" 
time="2018-09-01T14:45:28Z" level=info msg="Broadcasting from http://0.0.0.0:6077/" 
time="2018-09-01T14:45:28Z" level=info msg="EPG URL: http://0.0.0.0:6077/epg.xml"
```

Notice a few things:
 - The `version`, `branch`, and `revision` are empty just like #161
 - The M3U download fails
 - The username and passwords aren't masked out in the error messages

If I copy the URL exactly as-is from the error message, and paste it into VLC, it works.

**Comment by chazlarson** [comment]
Are the Docker container and VLC on the same machine?  If not, what happens if you try to retrieve the M3U outside telly on the same machine? [with curl or wget, perhaps]

**Comment by lellimecnar** [comment]
Yep, it's OVH... Any chance of using a VPN or a proxy?

**Comment by robbiet480** [comment]
Proxy support is in the forthcoming version of telly. VPN support is at the OS level, outside of telly's control. I've made a note to add a fat warning if we are unable to contact your provider to suggest it may be due to blocking like this.
