### ISSUE TITLE
 In Docker: unknown short flag '-b', try --help

### ISSUE THREAD

**Issue by abmurksi** [tellytv/telly#187]
**telly release with the issue:**

Container fails. Latest docker version from 05.09.2018

**Last working telly release (if known):**
before move to tellytv/telly

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

Docker on Debian 9 with Docker 18.06.1-ce
docker-compose 1.21.2

**Description of problem:**
Container immediately fails.

$ docker logs docker-compose_telly_1
app: error: unknown short flag '-b', try --help

Can not execute any commands via docker exec as it is immediately failing

docker-compose.yml:
version: '3'
services:
 telly:
    image: tellytv/telly
    ports:
      - 6077:6077
    environment:
      - TZ=Europe/Paris
      - TELLY_IPTV_PLAYLIST=https://api.init7.net/tvchannels.m3u
      - TELLY_WEB_LISTEN_ADDRESS=telly:6077
      - TELLY_IPTV_STREAMS=1
      - TELLY_DISCOVERY_FRIENDLYNAME=Tuner1
      - TELLY_DISCOVERY_DEVICEID=12345699
    command: -base=telly:6077

```

**telly or docker log:**
```
app: error: unknown short flag '-b', try --help
```

**Comment by guyspr** [comment]
This is actually not required to get it running in Docker. I see you are using the master branch, I recommend also checking out the dev version: https://github.com/tellytv/telly/tree/dev

This has some improvements like a config file instead of env variables.

**Comment by abmurksi** [comment]
Thanks. Moved to the dev-ffmpeg branch and got it working
