### ISSUE TITLE
Telly 1.5.0 CPU usage

### ISSUE THREAD

**Issue by BEisem** [tellytv/telly#192]
**telly release with the issue:**
telly, version 1.5.0 (branch: HEAD, revision: 811ea6be581f9bc8f2956d7c3892f2754b948e4d)
  build user:       root@8534dbdccf84
  build date:       20180907-03:23:00
  go version:       go1.10.3

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
macOS 10.12.6

**Description of problem:**

I assume this version of telly is using ffmpeg by default. Anyway, whenever I play a stream on my iPad, the CPU on the server machine is using about 100-120% of one core. Even worse, when I stop streaming, the CPU is still in use, and with each new stream, the CPU usage increases. Quitting telly is the only way to eliminate the CPU usage.

**Comment by robbiet480** [comment]
Taken care of by 7f69fc5618e071f61cf873bb14cc8bbf931e27eb
