### ISSUE TITLE
Adding XML TV Guide Provider breaks database

### ISSUE THREAD

**Issue by chazlarson** [tellytv/telly#197]
**telly release with the issue:**

```
➜  telly-1.5.0.linux-amd64 ./telly --version
telly, version 1.5.0 (branch: HEAD, revision: 5d61aa56231a40aa395b7079c38d4d6865b5dd0f)
  build user:       root@72ff8afbed41
  build date:       20180912-02:52:45
  go version:       go1.10.3
➜  telly-1.5.0.linux-amd64
```

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

Linux; Ubuntu 18.04

**Description of problem:**

Added Iris XMLTV link as a guide provider.  Brought up the lineup dialog, which cannot be closed per another issue.  reloaded page and IrisXML provider was no longer in the list.

Restarted telly, which will no longer start.
```
➜  telly-1.5.0.linux-amd64 ./telly
INFO[2018-09-12T06:08:02+02:00] telly is preparing to go live (version=1.5.0, branch=HEAD, revision=5d61aa56231a40aa395b7079c38d4d6865b5dd0f)
PANI[2018-09-12T06:08:02+02:00] error initializing video sources              error="sql: Scan error on column index 6: unsupported Scan, storing driver.Value type <nil> into type *json.RawMessage"
panic: (*logrus.Entry) (0xe83180,0xc4202324b0)

goroutine 1 [running]:
github.com/tellytv/telly/vendor/github.com/sirupsen/logrus.Entry.log(0x15cff60, 0xc4202353b0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/tellytv/telly/vendor/github.com/sirupsen/logrus/entry.go:126 +0x2d2
github.com/tellytv/telly/vendor/github.com/sirupsen/logrus.(*Entry).Panic(0xc420232460, 0xc4201a14e0, 0x1, 0x1)
	/go/src/github.com/tellytv/telly/vendor/github.com/sirupsen/logrus/entry.go:194 +0xaa
github.com/tellytv/telly/vendor/github.com/sirupsen/logrus.(*Entry).Panicln(0xc420232460, 0xc4201a1650, 0x1, 0x1)
	/go/src/github.com/tellytv/telly/vendor/github.com/sirupsen/logrus/entry.go:289 +0xd5
github.com/tellytv/telly/internal/context.NewCContext(0x15cff60, 0xc4201a1c78, 0x2, 0x2)
	/go/src/github.com/tellytv/telly/internal/context/context.go:92 +0xc95
main.main()
	/go/src/github.com/tellytv/telly/main.go:100 +0x5ce
➜  telly-1.5.0.linux-amd64
```

I have the database available upon developer request.  Not adding it to the case since it contains credentials.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**

**Comment by robbiet480** [comment]
Fixed via 924bdf3c2051b45631ce745f6a7db2b6cce91671
