### ISSUE TITLE
Crash during update with SD

### ISSUE THREAD

**Issue by warham28** [tellytv/telly#216]
I have this error when i start the update at 0:00 AM and the error disappear until 12:00 PM

[31mERRO[0m[2018-10-28T00:27:08-04:00] could not complete guide updates: error when updating schedule for provider 2: error getting lastModifieds from schedules direct: status code was 400, expected 2XX-3XX. received content: <html>
<head><title>400 Bad Request</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
</body>
</html>

Thanks!

**Comment by chazlarson** [comment]
Some more details?  What version of telly, other config details, how you "start the update"?  Does this error just appear in the log, or is there a user-visible effect?

**Comment by warham28** [comment]
Well... the problem disappear when i restart telly but appear again later... i use 1.5 version the latest... and the update is start via the web ui
