### ISSUE TITLE
How to set-up m3u playlist

### ISSUE THREAD

**Issue by harveydobson** [tellytv/telly#220]
**telly release with the issue:**
```
telly, version 1.5.0 (branch: HEAD, revision: d56d29269ca121a00d0cd2340b67be284a33f719)
  build user:       root@873a25215547
  build date:       20180916-03:58:34
  go version:       go1.10.3
```

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**
I'm working on Linux, Ubuntu 18 

**Description of problem:**
Hi All, 

I am having difficulty determining the correct commands to hook up my m3u playlist. One website told me to use:
`./telly --playlist="xyz.m3u" `

The readme documentation says to do this...

`./telly --iptv.playlist="abc.m3u" `

But in either case, it returns with 

`unknown shorthand flag: 'p' in --playlist=`  or `unknown shorthand flag: 'i' in --iptv.playlist=`, respectively.

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

I don't use telly.config.toml. Should I be? How do i do this?

```

**telly or docker log:**
This is the result when i run telly...  same as with using `./telly --help`, I don't get any indication of what I should be doing to load my m3u file as playlist and iptv.playlist are not there. 

```
Usage of ./telly:
  -c, --config.file string          Path to your config file. If not set, configuration is searched for in the current working directory, $HOME/.telly/ and /etc/telly/. If provided, it will override all other arguments and environment variables. $(TELLY_CONFIG_FILE)
  -d, --database.file string        Path to the SQLite3 database. If not set, defaults to telly.db. $(TELLY_DATABASE_FILE) (default "./telly.db")
      --log.level string            Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal] $(TELLY_LOG_LEVEL) (default "info")
      --log.requests                Log HTTP requests $(TELLY_LOG_REQUESTS)
      --version                     Show application version
  -l, --web.listen-address string   Address to listen on for web interface, API and telemetry $(TELLY_WEB_LISTEN_ADDRESS) (default ":6077")
unknown shorthand flag: 'p' in --playlist="/path/to/m3uplaylist.m3u"
```

**Comment by chazlarson** [comment]
Refer to the wiki for the most accurate information.  The readmes are branch-specific, and outside docs typically don’t identify which version they are referring to.

The syntax you reference is for 1.0 (master branch).
The config file method is used by 1.1 (dev branch).
1.5 is largely undocumented at this time as it’s an early alpha release.

1.1 is the most stable and most widely used.

**Comment by harveydobson** [comment]
Hi @chazlarson.

Thanks so much for the info!
