### ISSUE TITLE
Can't Get Telly To Run

### ISSUE THREAD

**Issue by ShaneH** [tellytv/telly#223]
I'm new to this and when I run it this is what I get.

C:\Windows\System32\Telly>telly.exe --iptv.playlist=C:\Users\shane\Telly\tv_channels_sandmannd_plus.m3u --listen 192.168.1.9:6077 --base=192.168.1.9:6077 --iptv.streams 5 --filter.regex=".*US.*"
Flag --iptv.playlist has been deprecated, use the configuration file instead.
unknown flag: --listen
Usage of telly.exe:
  -c, --config.file string          Path to your config file. If not set, configuration is searched for in the current working directory, $HOME/.telly/ and /etc/telly/. If provided, it will override all other arguments and environment variables. $(TELLY_CONFIG_FILE)
      --log.level string            Only log messages with the given severity or above. Valid levels: [debug, info, warn, error, fatal] $(TELLY_LOG_LEVEL) (default "info")
      --log.requests                Log HTTP requests $(TELLY_LOG_REQUESTS)
      --version                     Show application version
  -b, --web.base-address string     The address to expose via discovery. Useful with reverse proxy $(TELLY_WEB_BASE_ADDRESS) (default "localhost:6077")
  -l, --web.listen-address string   Address to listen on for web interface and telemetry $(TELLY_WEB_LISTEN_ADDRESS) (default "localhost:6077")
unknown flag: --listen

I don't get a config file or anything. I'm not sure what I'm doing wrong. Help please?

**Comment by chazlarson** [comment]
Refer to the walkthroughs in the wiki.  It appears that you have downloaded 1.1 and are attempting to run it in the 1.0 fashion.

The config file is a file you need to create.  There is a downloadable example and details in the wiki.
