### ISSUE TITLE
Plex on Nvidia Shield can't find Telly on Raspberry Pi

### ISSUE THREAD

**Issue by DanJayF** [tellytv/telly#225]
**telly release with the issue: 1.1.0.5 Beta**

**Operating environment: Standalone on Raspberry Pi running DietPi 6.19.7**

**Description of problem:**
I have Telly 1.1.0.5 running (seemingly successfully given the logs) on my Raspberry Pi 3 running DietPi 6.19.7. I have static IP addresses set on both the Pi and my Nvidia Shield which is running my Plex Server (1.14.1.5488).
I am able to access my Telly Proxy via my computer on my local network at http://192.168.86.50:6077/, the XML loads just fine. But in my Plex web interface when I go to add the DVR, i get the following error message, and it never finds telly automatically: https://i.imgur.com/Bownmub.png
I have a Google WIFI router so I'm not sure if it's blocking the connection or if it's my Nvidia Shield that is blocking Plex from accessing other local addresses via some sort of Firewall. I have "Always allow insecure connections" set to Always just in case, but it made no difference, including many reboots of all devices.

I have no idea what else to try, does anyone have any experience with a Nvidia Shield and/or a Raspberry Pi running telly? Telly seems to be running fine but I've had no luck at all adding it to Plex

**Contents of `telly.config.toml`:**
```
# THIS SECTION IS REQUIRED ########################################################################
[Discovery]                                    # most likely you won't need to change anything here
  Device-Auth = "telly123"                     # These settings are all related to how telly identifies
  Device-ID = 12345678                         # itself to Plex.
  Device-UUID = ""
  Device-Firmware-Name = "hdhomeruntc_atsc"
  Device-Firmware-Version = "20150826"
  Device-Friendly-Name = "telly"
  Device-Manufacturer = "Silicondust"
  Device-Model-Number = "HDTC-2US"
  SSDP = true

# THIS SECTION IS REQUIRED ########################################################################
[IPTV]
  Streams = 2               # number of simultaneous streams that the telly virtual DVR will provide
  Starting-Channel = 10000  # When telly assigns channel numbers it will start here
  XMLTV-Channels = true     # if true, any channel numbers specified in your M3U file will be used.
# FFMpeg = true             # if this is uncommented, streams are buffered through ffmpeg;
                            # ffmpeg must be installed and on your $PATH
                            # if you want to use this with Docker, be sure you use the correct docker image
# if you DO NOT WANT TO USE FFMPEG leave this commented; DO NOT SET IT TO FALSE

# THIS SECTION IS REQUIRED ########################################################################
[Log]
  Level = "info"            # Only log messages at or above the given level. [debug, info, warn, error, fatal]
  Requests = true           # Log HTTP requests made to telly

# THIS SECTION IS REQUIRED ########################################################################
[Web]
  Base-Address = "192.168.86.50:6077"   # Set this to the IP address of the machine telly runs on
  Listen-Address = "0.0.0.0:6077"       # this can stay as-is

# AT LEAST ONE SOURCE IS REQUIRED #################################################################
[[Source]]
  Provider = "Custom"
  Name = "Necro IPTV"
  M3U = "http://xtream-editor.com/en/get/m3u/REDACTED"
  EPG = "http://xtream-editor.com/en/get/epg/REDACTED"

# END TELLY CONFIG  ###############################################################################
```

**Command line used to run telly (run from /etc/rc.local):**
```
/root/telly &> /var/log/telly.log
```
(I have the **telly** binary in the root user's home folder)

**telly log:**
```
time="2019-01-03T20:52:05Z" level=info msg="telly is preparing to go live (version=1.1.0.5, branch=dev, revision=567f9062e94f32fd46bd6b82f10c1ac2e7f711c5)"
time="2019-01-03T20:52:05Z" level=info msg="Loading M3U from http://xtream-editor.com/en/get/m3u/REDACTED"
time="2019-01-03T20:52:07Z" level=info msg="Loading XMLTV from http://xtream-editor.com/en/get/epg/REDACTED"
time="2019-01-03T20:52:07Z" level=info msg="File (http://xtream-editor.com/en/get/epg/REDACTED) is gzipp'ed, ungzipping now, this might take a while"
time="2019-01-03T20:52:58Z" level=info msg="Loaded 205 channels into the lineup from Necro IPTV"
time="2019-01-03T20:52:58Z" level=info msg="telly is live and on the air!"
time="2019-01-03T20:52:58Z" level=info msg="Broadcasting from http://0.0.0.0:6077/"
time="2019-01-03T20:52:58Z" level=info msg="EPG URL: http://0.0.0.0:6077/epg.xml"
```

**Comment by chazlarson** [comment]
Can you ssh to the shield?  If so, what does `curl -fLv http://192.168.86.50:6077/` show from the shield?

Is Plex running in a container on the shield?

**Comment by chazlarson** [comment]
Also, consider bringing this to the support channel on the Discord.  More eyes.

**Comment by DanJayF** [comment]
That's a good idea @chazlarson, I will need to install an SSH server on it when I get access to it again and will give that a go. I'll revert with what I find.
No it's just the default Play Store NVidia Shield version of Plex Media Server that's running on it.

I'll create a Discord account after I get to try the above. Thanks

**Comment by DanJayF** [comment]
So I figured out the issue.
I installed a terminal emulator on the Shield and after a lot of pinging and tracerouting, I found it couldn't access my LAN because I had forgotten to disconnect from ExpressVPN 🤦🏻‍♂️
As soon as I disabled that, Plex found telly and it installed normally. I'm now just waiting for the guide to download.

False alarm!
