### ISSUE TITLE
Building telly from the git repository?

### ISSUE THREAD

**Issue by elbow** [tellytv/telly#226]
HI,

I cloned telly repository; I'm new to golang but thought I might like to make adjustments.

But how to build telly?  

When I "make" the Makefile the "go fmt" fails like so:

`>> formatting code
can't load package: package _/home/steve/telly: cannot find package "_/home/steve/telly" in any of:
	/usr/lib/go-1.10/src/_/home/steve/telly (from $GOROOT)
	/home/steve/go/src/_/home/steve/telly (from $GOPATH)
can't load package: package _/home/steve/telly/internal/go-gin-prometheus: cannot find package "_/home/steve/telly/internal/go-gin-prometheus" in any of:
	/usr/lib/go-1.10/src/_/home/steve/telly/internal/go-gin-prometheus (from $GOROOT)
	/home/steve/go/src/_/home/steve/telly/internal/go-gin-prometheus (from $GOPATH)
can't load package: package _/home/steve/telly/internal/m3uplus: cannot find package "_/home/steve/telly/internal/m3uplus" in any of:
	/usr/lib/go-1.10/src/_/home/steve/telly/internal/m3uplus (from $GOROOT)
	/home/steve/go/src/_/home/steve/telly/internal/m3uplus (from $GOPATH)
can't load package: package _/home/steve/telly/internal/providers: cannot find package "_/home/steve/telly/internal/providers" in any of:
	/usr/lib/go-1.10/src/_/home/steve/telly/internal/providers (from $GOROOT)
	/home/steve/go/src/_/home/steve/telly/internal/providers (from $GOPATH)
can't load package: package _/home/steve/telly/internal/xmltv: cannot find package "_/home/steve/telly/internal/xmltv" in any of:
	/usr/lib/go-1.10/src/_/home/steve/telly/internal/xmltv (from $GOROOT)
	/home/steve/go/src/_/home/steve/telly/internal/xmltv (from $GOPATH)
Makefile:22: recipe for target 'format' failed
make: *** [format] Error 1
`
Thanks,
@elbow

**Comment by chazlarson** [comment]
I'm also new to the golang toolchain, but here's a script that works on my Mac to do a scorched-earth build:

```
#!/bin/bash

#!/bin/bash

DIR="${GOPATH}/src/github.com/"
if [ -d $DIR ]; then
  cd "$DIR"
  rm -fr tellytv
fi

go get github.com/tellytv/telly
cd "${DIR}tellytv/telly"
git checkout master

dep ensure

make promu
make
```

Then once that succeeds you can go into `${GOPATH}/src/github.com/tellytv/telly` and switch branches:
```
git checkout dev
dep ensure
make
```
