### ISSUE TITLE
EPG Update

### ISSUE THREAD

**Issue by 12nick12** [tellytv/telly#227]
**telly release with the issue:**

**Last working telly release (if known):**

**Operating environment (Docker/Windows/Linux/QNAP, etc.):**

**Description of problem:**
EPG doesn't update automattacly in Plex. I'm not sure if this is a telly or Plex issue. I have telly update the EPG and it didn't pull anything. I restarted telly which redownload the epg from the provider then stuff showed up. Should I just have telly reboot every night to download the new EPG?

**Contents of `telly.config.toml` [if you're using a version above 1.1]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```toml

```

**Command line used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**Docker run command used to run telly [if applicable]:**
- REMEMBER TO DELETE ANY CREDENTIALS IN CONFIG FILES OR COMMAND LINES
```

```

**telly or docker log:**
```

```

**Additional information:**

**Comment by chazlarson** [comment]
You're correct, telly 1.1 only updates EPG at startup; restarting it every night might be overkill, depending on your channels, but yes, at this point the only way to update EPG with telly 1.1 is to restart it.

**Comment by elbow** [comment]
> You're correct, telly 1.1 only updates EPG at startup; restarting it every night might be overkill, depending on your channels, but yes, at this point the only way to update EPG with telly 1.1 is to restart it.

Hi,

Do the developers recommend that we use 1.5 rather?  

If I restart telly I presumably will break recordings in progress, and I can't find any obvious way to tell if telly is busy with a stream or not.  It logs when it "tunes" a channel but not when the connection ends.

What's the advice?

Thanks,
Elbow

**Comment by chazlarson** [comment]
1.5 has its own issues around EPG, primarily that it doesn't auto-flush old entries so your database will grow without end.  Presently you would need to periodically run some SQL on the database to clear out old entries, which, of course, would require you to shut it down, so you're back in the same situation.

I found a shell script here which purports to tell you if Plex is recording; perhaps this would work to identify a safe restart time?

https://forums.plex.tv/t/check-if-a-dvr-recording-is-in-progress-via-the-api/185736/2

**Comment by elbow** [comment]
OK - I looked at routes.go and if I understand correctly, telly can't tell me whether it is currently streaming a channel or not because it actually just sends the client (Plex) a "moved permanently" and so it doesn't know after that what happens.

Which should mean that restarting telly won't actually interrupt Plex who is getting the stream directly from the provider and not "via" telly.

Is my logic right?  If it is I will just stop and start the telly service at some time before Plex tries to update its own EPG.

Thanks

**Comment by chazlarson** [comment]
That's correct, if you are not using ffmpeg.  

If ffmpeg is not enabled [which is the default], telly just gives plex a redirect to the provider stream.

If you have ffmpeg enabled, telly retrieves the stream itself and runs it through ffmpeg on the way to plex.

**Comment by chazlarson** [comment]
Closing since this seems to be sorted.
