### ISSUE TITLE
Parameter -temp & -Useregex not working on Windows

### ISSUE THREAD

**Issue by haxcop** [tellytv/telly#58]
Hi, there's some issues on the windows 64 release
As you can see bellow the local directory exist but telly someshow is unable to finish the creation of the file and fails.
As i could see on discord you have solve this on linux and it would be nice to have it too on Windows.

`PS C:\Users\Carlos\Documents\tools> telly-windows-amd64.exe -playlist="http://api.vaders.tv/vget?username=username&password=password&format=ts" -streams 5 -friendlyname "MIX"-useregex 'usa|spain' -logrequests
[telly] [info] booting telly v0.4.4
[telly] [error] Could not create file: C:\Users\Carlos\AppData\Local\Temp ; open C:\Users\Carlos\AppData\Local\Temp: is a directory`

if the temp file is definded it will work for example `-temp C:\Users\Carlos\AppData\Local\Temp\filename`

**Comment by HazCod** [comment]
Weird, as the default value is `os.TempDir()+"/telly.m3u"`.
From the docs: 

    On Windows, it uses GetTempPath, returning the first non-empty value from %TMP%, %TEMP%, %USERPROFILE%, or the Windows directory.

**Comment by haxcop** [comment]
Hi @HazCod  sure is in the details above but anyway here's again 
%TEMP% & %TMP% = C:\Users\Carlos\AppData\Local\Temp < Are the same
%USERPROFILE% = Carlos

**Comment by tombowditch** [comment]
Backslash vs forward slash @HazCod ?

**Comment by HazCod** [comment]
Aha! Perhaps we should use `os.path.Join(os.TempDir(), "telly.m3u")`

**Comment by erlebc** [comment]
I'm not a developer by trade, and I know you guys are building bundles / executables for multiple plaforms.  I'm on a Win 10 64-bit also, and see the same issue that @haxcop reported.  I can see in the https://github.com/tombowditch/telly/tree/fix-tempdefault  directory there is a new file called main.go, but I presume this would be for a platform where the source files can be replaced and then simply re-executed?  
I downloaded the telly-windows-386.exe just a few minutes ago quite a while after @HazCod's update.  I'm just trying to see if I should wait for a new Windows build before trying this again?

I love what you guys are trying to do.  I've spent a ton of time looking around for a good IPTV player, and while there are some out there, there are none which work on PLEX.

**Comment by HazCod** [comment]
@erlebc @haxcop try this build
[telly-windows-fixtmpdefault.exe.zip](https://github.com/tombowditch/telly/files/1788210/telly-windows-fixtmpdefault.exe.zip)

**Comment by erlebc** [comment]
@HazCod - Sorry, but I get the same behavior with the updated build.

C:\Users\Dad\Downloads\telly-windows-fixtmpdefault.exe>telly-windows-fixtmpdefault -playlist=https://tinyurl.com/y7vqnx2u -useregex .*US*.
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\Dad\AppData\Local\Temp ; open C:\Users\Dad\AppData\Local\Temp: is a directory

**Comment by haxcop** [comment]
@HazCod I have tried and is the same story - fails to create the file 
PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-windows-fixtmpdefault.exe\telly-windows-fixtmpdefault.exe -play
list "https://blablabla/123456"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clo\AppData\Local\Temp ; open C:\Users\clo\AppData\Local\Temp: is a directory
PS C:\WINDOWS\system32>

BTW: @erlebc for your own benefit do not post your actual public playlist here - i'll recommend to edit the url posted above

**Comment by erlebc** [comment]
@haxcop.  Thanks for the heads up.  I didn't realize I had exposed myself there.  I've updated the comment, and appreciate you pointing it out.

**Comment by erlebc** [comment]
Would you guys have a time line for a fix for this Windows problem?

**Comment by haxcop** [comment]
@erlebc you can use a destination path for now as a workaround before its fixed

**Comment by erlebc** [comment]
I assume you refer to the -temp flag on the telly executable.  I have tried
using that flag with various directories.  Some of which I created, and
others which are already present and should have read / write on them.   I
always get the same message:

C:\Users\Dad\Downloads\telly-windows-fixtmpdefault.exe>telly-windows-fixtmpdefault
-playlist=https://someurl.com -temp=C:\ -useregex=.*US*.
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\ ; open C:\: is a directory

**Comment by haxcop** [comment]
@erlebc you need to do it something like this 
`-temp "C:\users\erlebc\anyfolder\FILE_NAME_OF_YOUR_CHOICE" -useregex 'United States'`
The `-useregex` is case sensitive, so ill recommend to have a look at your m3u file and check the how the group channels are written i.e. On Vaders is United States
give it a go now :)

**Comment by erlebc** [comment]
Thank You Carlos.  Able to get telly to parse my list and listen now.  It
also did take the one string I used with the -useregex flag.  Do you allow
chaining of multiple strings?  In my list there are multiple groups which
I'd like to bring in such as Movies, Sports, etc.  I tried a comma
separator, but that resulted in 0 channels being loaded.  When I used a
single argument/string then it found 97 channels and started up fine.   I
was hoping the flag allowed for multiple strings if one uses the proper
syntax.

One other comment, and this is probably expected behavior, but I wanted to
check.  I've got pretty fast Internet to my home (35X5).  I chose an EPG
from a list and realize I may need to play around with them to find the
best accuracy, but even with this speed PLEX is taking around an hour to
update the list.  Does that sound right to you?

**Comment by haxcop** [comment]
@erlebc You Welcome. 
You can use the syntax `-useregex 'Ireland|United Kingdom|Sports'` for groups or channels required of your preference and `-filterregex ` for the unwanted ones. 
I clear this in a combined way "for now" with two other scripts and powershell which basically can sort and delete the duplicated channels normally found on m3u list and gives you a cleaner xml epg file according to your filters - which you can then avoid the filtering with telly
You can find more about here [https://github.com/haxcop/Remove_Dupe_Rows_From_File](url)
and here [https://github.com/jjssoftware/m3u-epg-editor](url)

for your second Q: this will generally take a lot of time at the first time and it;s not based on your internet speed- is in the api calls from/to Gracenote / Plex
You can speed it up Disabling Enhanced Program Guide
![capture](https://user-images.githubusercontent.com/7826906/37475901-b09b4046-286b-11e8-92c7-34319d8824a0.PNG)

**Comment by erlebc** [comment]
@hazcop:  I really appreciate your assistance as I think this is going to be a fantastic addition to PLEX.  However, now that I am attempting to use the pipeline separator for -filterregex and -useregex I either am back to the "cannot create directory" error, or, if I move the -temp flag more to the front of the command, then it will run, but I don't believe any filtering of the playlist is happening based on the results shown here:    (I tried using double and single quotes around the filtering sets, but observed no different results from what I am posting here)

C:\Users\Dad\Downloads\telly-windows-fixtmpdefault.exe>telly-windows-fixtmpdefault -playlist=https://someurl.com -filterregex "Bein|uk|UK|Kids|Sports Pass|International Sports" -temp=C:\users\dad\tellytemp\sample -useregex "English|Sports|Movies|News Networks"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\Dad\AppData\Local\Temp ; open C:\Users\Dad\AppData\Local\Temp: is a directory

C:\Users\Dad\Downloads\telly-windows-fixtmpdefault.exe>telly-windows-fixtmpdefault -playlist=https://someurl.com -filterregex "Bein|uk|UK|Kids|Sports Pass|International Sports" -useregex "English|Sports|Movies|News Networks" -temp=C:\users\dad\tellytemp\sample
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\Dad\AppData\Local\Temp ; open C:\Users\Dad\AppData\Local\Temp: is a directory

C:\Users\Dad\Downloads\telly-windows-fixtmpdefault.exe>telly-windows-fixtmpdefault -playlist=https://someurl.com -temp=C:\users\dad\tellytemp\sample -filterregex "Bein|uk|UK|Kids|Sports Pass|International Sports" -useregex "English|Sports|Movies|News Networks"
[telly] [info] booting telly v0.4.5
[telly] [info] Downloading file https://tinyurl.com/y7vqnx2u to C:\users\dad\tellytemp\sample
[telly] [info] Reading m3u file C:\users\dad\tellytemp\sample...
[telly] [info] telly is currently not filtering for only uk television. if you would like it to, please use the flag -uktv
[telly] [info] found 1890 channels

* * * * * * * * * * *
[telly] [warning] telly has loaded more than 420 channels. Plex does not deal well with more than this amount and will more than likely hang when trying to fetch channels. You have been warned!

**Comment by haxcop** [comment]
@erlebc THe -filterregex seems to be working correctly on telly and that's the reason i use a separate scripts as mentioned above
the `-temp` needs to be just after the `-playlist` 

with the above scripts i do something like this into a PowerShell.ps1
# Set your folder test location
Set-Location C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests
# Declare your variables below
$1 = "C:\Users\Carlos\Documents\Plex-Scripts\development\m3u-epg-editor\newfile.py"
$2 = "C:\Python27\python.exe"
$A = "http://api.vaders.tv/vget?username=xxxxxx&password=xxxxxxx&format=ts"
$B = "http://vaders.tv/p2.xml.gz"
$C = "'sports','ireland','united kingdom','latino','united states'"
$D = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests"
$E = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\unsorted"
$F = "'26 tv hd','a&e lt hd','amc lt hd','axn lt hd','animal planet hd lt','azteca 13','azteca 7','bandamax lt','cbn hd','cbs news hd','cbs sports hq','cnn lt','canal 11','canal de las estrellas','cinecanal','comedy central lt','de pelicula','discovery channel lt hd','discovery civilization','discovery home & health','discovery science lt','discovery theater','discovery turbo lt','disney jr lt','disney lt hd','disney xd lt','e! lt','espn 2 lt','espn 3 lt','espn lt','fight tyme','fox action lt','fox cinema lt','fox movies lt','fox sports 2 lt hd','fox sports 3 lt hd','fox sports carolina hd','fox sports indiana hd','fox sports lt hd','fox sports south georgia hd','fox sports south georgia hd','fox sports tennessee hd','fox sports tennessee hd','galavision hd','hbo family lt hd','hbo lt hd','hbo plus lt hd','hbo signature lt hd','history lt hd','mimusica hd','nbc philadelphia','nbc universo 2 hd','nbc universo 2 hd','nbc universo hd','nbc universo hd','nat geo lt','nat geo wild lt','osn cricket hd','rds 2','sony lt','spectrum sportsnet hd','spectrum sportsnet la hd','tva sports hd','telemundo los angeles hd','unimas hd','univision miami hd'"
$G = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\sorted"
$H = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\sorted.m3u8"
$I = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\original_dupe_row.m3u8"
$uc = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\unsorted.channels.txt"
$ccng = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\channels_cleaned_nogroup.txt"
$filename_sd = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\cleaned_final_channels-sd.txt"
$filename_hd = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\cleaned_final_channels-hd.txt"
$IPTVSD = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\sd.txt"
$IPTVHD = "C:\Users\Carlos\Documents\Plex-Scripts\development\telly\tests\hd.txt"
$file = $H 
$NewFile = $I 

# Run the first script

C:\Python27\python.exe C:\Users\Carlos\Documents\Plex-Scripts\development\m3u-epg-editor\newfile.py --sortchannels --m3uurl="$A" -e="$B" -g "$C" --channels="$F" --outdirectory="$D" --outfilename="$G"

# Start the Second 

$hash = @{}                       # Define an empty hashtable
Get-Content $file |               # Send the content of the file into the pipeline... 
    ForEach-Object {              # For each object in the pipeline...
    # note '%' is an alias of 'foreach-object'          
    if ($hash.$_ -eq $null) {
        # if that line is not a key in our hashtable...
        # note -eq means 'equals'
        # note $_ means 'the data we got from the pipe'
        # note $null means NULL
        $_                        # ... send that line further along the pipe
    };
    $hash.$_ = 1                  # Add that line to the hash (so we won't send it again)
    # note that the value isn't important here,
    # only the key. ;-)
} > $NewFile  # finally... redirect the pipe into a new file. 
Get-ChildItem $NewFile | ForEach-Object {
    # get the contents and replace line breaks by U+000A
    $contents = [IO.File]::ReadAllText($_) -replace "`r`n?", "`n"
    # create UTF-8 encoding without signature
    $utf8 = New-Object System.Text.UTF8Encoding $false
    # write the text back
    [IO.File]::WriteAllText($_, $contents, $utf8)
}
# Start Telly 
telly-windows-amd64.exe -playlist="$I" -streams 5 -friendlyname "MIX" -deviceid "00000001" -listen "127.0.0.1:1077"

> FYI This Script still in Development but just to give you an IDEA

**Comment by HazCod** [comment]
Can you guys see if following build fixes the issue?

[telly-fix2.zip](https://github.com/tombowditch/telly/files/1832550/telly-fix2.zip)

**Comment by haxcop** [comment]
@HazCod Thanks for the release but it not Fixed have a look at the output below with different tests 

> PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

> PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist="http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist= "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file ...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist = "http://api.vaders.tv/vget?username=
xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file =...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist 'http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist='http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist = 'http://api.vaders.tv/vget?username=
xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file =...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2

**Comment by haxcop** [comment]
Closed by mistake. 
@HazCod  here's the output - remains the issue. 

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist="http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist= "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file ...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist = "http://api.vaders.tv/vget?username=
xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file =...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist "http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts"
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist 'http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist='http://api.vaders.tv/vget?username=xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [error] Could not create file: C:\Users\clozada\AppData\Local\Temp ; open C:\Users\clozada\AppData\Local\Temp: is a directory

>PS C:\WINDOWS\system32> C:\Users\clozada\Downloads\telly-fix2\telly.exe -playlist = 'http://api.vaders.tv/vget?username=
xxxx&password=xxxx&format=ts'
[telly] [info] booting telly v0.4.5
[telly] [info] Reading m3u file =...
[telly] [error] unable to read m3u file, error below
[telly] [error] m3u files need to have specific formats, see the github page for more information
[telly] [error] future versions of telly will attempt to parse this better
panic: Unable to open playlist file

goroutine 1 [running]:
main.main()
        /Users/niels/Downloads/telly/main.go:183 +0x1bc2
>PS C:\WINDOWS\system32>

**Comment by HazCod** [comment]
Another try: 
[telly-fix3.zip](https://github.com/tombowditch/telly/files/1833309/telly-fix3.zip)

**Comment by haxcop** [comment]
@HazCod Same error

**Comment by haxcop** [comment]
@HazCod For some Weird reasson (probably an API Request from telly?) the `-useregex 'A | B | C'` stoped working. i have tried on Telly Versions : 4.4 / 4.5 / and the latest build given on issue #77 - and the -filterregex either.

**Comment by myusuf3** [comment]
not sure if this is right place, but how are you guys handling getting accurate guides into plex dvr for vaders? Can i provide this link somewhere for plex to consume? `http://vaders.tv/p2.xml.gz` ?

**Comment by Latiron** [comment]
@myusuf3 This is not the right place for your particular post.  This is an open issue related to something totally different.  EIther open a new issue, or join the Discord Telly group and ask in the support channel.  Thanks.
