### ISSUE TITLE
use -useregex and -filterregex to take a .txt file

### ISSUE THREAD

**Issue by haxcop** [tellytv/telly#64]
Feature request: 

> I use a set of scripts in an automated way for now to archive an Unique file that can be use in combination with telly 

It will be more handy in some cases if is possible to use the power of use:
`-useregex` & `-filteregex` from a `"newfileName.txt"` 
as an alternative for large selection of channels, groups, country's, etc...

this came up as the result of using other scripts in combination with `telly` 
for an easy and clear example this can be archive in the following way.

`C:\Python27\python.exe C:\m3u-epg-editor.py -m="http://iptv...=ts" --epgurl="http://epg.xml.gz" -g="'sports','spain'" -d="C:\telly" -f="C:\telly\mix"`

With this script you can filter the original files `m3u & xml` and will give you also two (2) files.txt 

1. `no_epg_channles.txt`
2. `mix.txt`

So here it comes the action

I take Powershell  and `gc $mix| sort | get-unique > $newfileName `

## Now  
` telly -useregex  "C:\telly\newfileName.txt" -filteregex "C:\telly\no_epg_channles.txt" 
instead of the current way of `telly -filteregex "'a'|'b'|...|'z'"`

This is all accomplished in an automated way (not all the scripts are full disclosure)

**Comment by tombowditch** [comment]
Unrelated in the new versions.
